### PR TITLE
Setup

### PR DESCRIPTION
**Pull request by Somdotta07**
- Set up with Create-React-App
- Set up linters
- Add React-Router-Dom
- Add Redux
- Add @reduxjs- toolkit
- Add React-Redux
- Add Redux-thunk
- Add Redux-logger
Front-end 1st PR
r

### CODE REVIEW

**Comment by o-rashad** [comment]
Working on it @Somdotta07 @Kingstalux :+1:

**Comment by od-c0d3r** [comment]
Hey @Somdotta07 @Kingstalux ^^!
I just wanted to ask..
Should the PR be from `feature` to `development` branch ?, or there is something I'm missing

**Review by o-rashad — COMMENTED** [review]
Hey @Somdotta07 @Kingstalux ^^!
I just wanted to ask..
Should the PR be from `feature` to `development` branch ?, or there is something I'm missing

**Comment by Somdotta07** [comment]
Hi @od-c0d3r ,
Thanks for asking that question.
We are creating all the pull requests into the feature branch now, after finalizing the application we will create the pull request for the Development branch. Final PR will be submitted from Development to the main branch.

**Review by o-rashad — APPROVED** [review]
Asslam Alaikum @Somdotta07 @Kingstalux  ,😊

Hi👋🏽, 
`Thanks for your clarification, i get it now and can understand your work flow better.` :100: 
Your project is complete!  
There is nothing else to say other than... it's time to merge it 😎 

# Congratulations! 🎉 

Happy coding!👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
